### ISSUE TITLE
[TODO]: Redo home page layout

### ISSUE THREAD

**Issue by lwthatcher** [byuhci/stickers-2#6]
# Home Page Layout
Part of our plan is to make this look better.

## Progress
- [x] dataset drop-down
- [x] label scheme drop-down
- [x] has energy icon
- [x] has video icon
- [x] default dataset
- [ ] group by projects

**Comment by lwthatcher** [comment]
Also includes a "can-sync" icon.
I'll leave the grouping by projects for another time.
